# -*- coding: utf-8 -*-
"""question-answering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/178J1zwqc_FiDcZ_dlnbXLStnrvmUvwMb
"""

!pip install transformers

from transformers import pipeline

vqa_pipeline = pipeline('visual-question-answering')

image = r'/content/cute-cat-isolated-on-solid-background-photo.jpg'

question = input("enter a question to ask about image:")
result = vqa_pipeline(image, question)
print(result,end=" ")

